-- 1. Customer Table
CREATE TABLE Customer (
    CUSTOMERID VARCHAR(6) PRIMARY KEY,
    FULLNAME VARCHAR(100),
    EMAIL VARCHAR(100),
    COMPANYNAME VARCHAR(100)
) ENGINE=InnoDB;

-- 2. DemoRequest Table
CREATE TABLE DemoRequest (
    DEMOREQUESTID VARCHAR(9) PRIMARY KEY,
    CUSTOMERID VARCHAR(6),
    INTERESTAREA VARCHAR(255),
    REQUESTEDDATE DATE,
    REQUESTSUBMISSIONDATE DATE,
    FOREIGN KEY (CUSTOMERID) REFERENCES Customer(CUSTOMERID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 3. Event Table
CREATE TABLE Event (
    EVENTID VARCHAR(10) PRIMARY KEY,
    EVENTNAME VARCHAR(100),
    EVENTDATETIME DATETIME
) ENGINE=InnoDB;

-- 4. EventParticipation Table
CREATE TABLE EventParticipation (
    EVENTID VARCHAR(10),
    CUSTOMERID VARCHAR(6),
    PRIMARY KEY (EVENTID, CUSTOMERID),
    FOREIGN KEY (EVENTID) REFERENCES Event(EVENTID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (CUSTOMERID) REFERENCES Customer(CUSTOMERID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 5. Admin Table
CREATE TABLE Admin (
    ADMINID VARCHAR(6) PRIMARY KEY,
    FULLNAME VARCHAR(100),
    PASSWORD VARCHAR(25)
) ENGINE=InnoDB;

-- 6. Feedback Table
CREATE TABLE Feedback (
    feedbackID INT AUTO_INCREMENT PRIMARY KEY,
    customerID VARCHAR(6) NOT NULL,
    interestArea VARCHAR(255),
    rating INT,
    comments TEXT,
    submissionDate DATE,
    followup_status VARCHAR(50),
    followup_notes TEXT,
    FOREIGN KEY (customerID) REFERENCES Customer(CUSTOMERID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB;
